kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: bradbot1
    password: 
      from_secret: access_token
    repo: bradbot1/gitea-forwarder
    tags: latest

trigger:
  branch:
  - master